--- #YAML:1.0
name: Test-XML
version: 0.05
license: perl
distribution_type: module
requires:
  Test::More: 0
  XML::SemanticDiff: 0.95
recommends:
  XML::SAX: 0
  XML::SAX::Writer: 0
  XML::Twig: 0
  XML::XPath: 0
build_requires: {}
conflicts: {}
provides:
  Test::XML:
    file: lib/Test/XML.pm
    version: 0.05
  Test::XML::SAX:
    file: lib/Test/XML/SAX.pm
    version: 0.01
  Test::XML::Twig:
    file: lib/Test/XML/Twig.pm
    version: 0.01
  Test::XML::XPath:
    file: lib/Test/XML/XPath.pm
    version: 0.02
generated_by: Module::Build version 0.18
